### ISSUE TITLE
通过HFS安装该开发板的问题

### ISSUE THREAD

**Issue by RealWangzhihong** [DeqingSun/ch55xduino#102]
由于没办法在开发板管理器中找到CH55X的支持包，所以我想通过HFS建立本地下载服务，但是不知道应该下载哪些文件用于HFS，或者说怎么用HFS达到安装的目的，可以帮忙指导吗，谢谢

**Comment by RealWangzhihong** [comment]
https://blog.csdn.net/weixin_42880082/article/details/127067913
我参考的是这篇文章里的安装方式，但是文章里并没有描述清楚利用HFS安装开发板包的过程

**Comment by DeqingSun** [comment]
请自行阅读并修改
```https://raw.githubusercontent.com/DeqingSun/ch55xduino/ch55xduino/package_ch55xduino_mcs51_index.json```

如果你做不到，请自行学习科学上网。
