### ISSUE TITLE
remove mDelay functions

### ISSUE THREAD

**Issue by nerdralph** [DeqingSun/ch55xduino#11]
Since ch55xduino implements delay() and delayMicroseconds(), there is no point using the mDelay functions.
https://github.com/DeqingSun/ch55xduino/blob/ch55xduino/ch55xduino/ch55x/cores/ch55xduino/debug_util.c

**Comment by DeqingSun** [comment]
delayMicroseconds is not implemented yet. mDelay is used in init() and other places. I'll see if it is safe to replace them with Arduino's delay.

**Comment by DeqingSun** [comment]
fixed with https://github.com/DeqingSun/ch55xduino/commit/5d695e3e4d5bfe41c36b36262f1a9be382d87738
