### ISSUE TITLE
Serial1_read() Strange Problems;

### ISSUE THREAD

**Issue by hanbingniao1** [DeqingSun/ch55xduino#110]
很抱歉再次打扰，经过多次验证，发现Serial1_read()确实有问题。具体是这些代码在单独的文件中运行正常，但是在我代码量较大的
程序里加入后，Serial1_available（）获取正常，但是只要加上Serial1_read()，Serial1_available（）就会变成01，经过多次测试，并且多次
查看了我的其他代码，理论上没有任何关联，我尝试将代码单独使用，发现某些时候是正常，有些时候是错误的，很玄学，这有可能是哪里的问题呢？对不起，
也许是个小问题，上一个issue表达不清，可能您误以为是一个c语言学习的问题了。我已经研究了很长时间，仍未解决，很抱歉耽误您的时间，感谢您
对ch55x的arduino支持库的开发，让我这种菜鸟也能方便开发ch552单片机程序，谢谢！

**Comment by hanbingniao1** [comment]
![搜狗截图20230127003326](https://user-images.githubusercontent.com/108322768/214896877-4789eeb0-3f0e-4e10-9f9d-a3948a0cd13a.png)
![搜狗截图20230127003254](https://user-images.githubusercontent.com/108322768/214896884-e2131d8a-ff2e-4182-b413-d212652b140e.png)

**Comment by hanbingniao1** [comment]
已解决；；不知道是否是缓冲区那边有问题，加了一堆nop之后可用了

**Comment by DeqingSun** [comment]
很有可能和 https://github.com/DeqingSun/ch55xduino/issues/107 是同一个问题，请等两天我更新版本再试一下。

**Comment by DeqingSun** [comment]
0.0.17应该修复了这个问题。
