### ISSUE TITLE
How to use about attachInterrupt's mode(RISING OR CHANGE)?

### ISSUE THREAD

**Issue by wukongxuetang** [DeqingSun/ch55xduino#111]
interrupt example only FALLING mode,if use RISING or CHANGE will get error,It is "error 20: Undefined identifier 'RISING'"
  
attachInterrupt(0, int0Callback, FALLING);//P3.2
attachInterrupt(1, int1Callback, FALLING);//P3.3

**Comment by DeqingSun** [comment]
Ch552 only support falling or low.
