### ISSUE TITLE
Could not to upload

### ISSUE THREAD

**Issue by bigersmoke** [DeqingSun/ch55xduino#116]
After installing the driver with zadig, the PC can recognize the device, but when I try to upload with arduino, an error will be reported.
The following is the error message:

Load file as hex
   Loaded 4813 bytes between: 0000 to 1317
ch375Version 35
CH375GetUsbID 0
DeviceVersion of CH55x: 2.50 
Send Detect: Fail

**Comment by DeqingSun** [comment]
Looks like a driver conflict.

You do not need to use zadig. Please uninstall the driver completely and let windows install the ch375 driver automatically.
