### ISSUE TITLE
RTS and DTR on USBSerial

### ISSUE THREAD

**Issue by ogogon** [DeqingSun/ch55xduino#119]
Tell me, please, if I use USBSerial to interact my program in ch55xduino with an external computer, is it possible for me to programmatically determine that this external computer changes the states of the RTS and DTR signals from its side of the USB com port?

Thanks in advance,
Ogogon.

**Comment by DeqingSun** [comment]
Yes

https://github.com/DeqingSun/ch55xduino/issues/48

**Comment by ogogon** [comment]
Thank you very much! This is very optimistic for me!

I believe that within a week I will receive my module with 552T and try to implement it.
Can I ask additional questions?

Ogogon.
