### ISSUE TITLE
Would CH552 Chip  work with cheap 433 mhz RF transmitter and receivers ?

### ISSUE THREAD

**Issue by happytm** [DeqingSun/ch55xduino#123]
I wanted to use CH552 variant with cheap 433 mhz transmitter and receiver combo like link below:

https://lastminuteengineers.com/433mhz-rf-wireless-arduino-tutorial/

Is it possible ?

Thanks.

**Comment by DeqingSun** [comment]
It will possible if you are able to port the Radiohead library

**Comment by happytm** [comment]
OK thanks for your quick reply.
