### ISSUE TITLE
What is the corresponding pin number when use RST as Input?

### ISSUE THREAD

**Issue by cuijiemmx** [DeqingSun/ch55xduino#128]
I want to use the RST pin as Input, what's the pin number for it if I use digitalRead(pin number for RST) to get input value?

**Comment by DeqingSun** [comment]
Reset pin is not included in the digitalread function, you need to read bRST bit in CLOCK_CFG register.

**Comment by cuijiemmx** [comment]
@DeqingSun Can you post an example? I've been trying for hours and it still doesn't work

**Comment by DeqingSun** [comment]
I don't have hardware now but I think you can try ```CLOCK_CFG&bRST```.

I don't remember if the configuration settings from CH552 enable or disable RST pin, and you can check with the official ISP tool. If it is not what you wanted, you may refer to https://github.com/DeqingSun/ch55xduino/issues/125 to bypass the configuration writing to keep the configuration unchanged.

**Comment by cuijiemmx** [comment]
@DeqingSun thanks for your information, it finally works with following steps
1. use !!(CLOCK_CFG & bRST) to check button press state, compile
2. disable manually reset function in ISP tool, then download hex to chip
