### ISSUE TITLE
CH552 CMISIS DAP

### ISSUE THREAD

**Issue by sabas1080** [DeqingSun/ch55xduino#13]
Hi @DeqingSun 

First of all thank you for your work

I am triying your code for CMISIS DAP with CH552, but but I can't see the usb port of the device, is there any reference that it should appear?

Thanks

**Comment by DeqingSun** [comment]
What you mean usb port? It should appear as an HID device.

**Comment by sabas1080** [comment]
@DeqingSun I have bootloadwer 2.4, it can be that?

when the chip is in bootloader mode it appears the device USB and I can program with wchisptool, but when I load the compiled example, everything disappears

With bootloader 2.4, I can't upload directly from arduino

```
------------------------------------------------------------------
CH55x Programmer by VNPro
------------------------------------------------------------------
Load file as hex
   Loaded 1977 bytes between: 0000 to 07E6
Found Device CH552
Bootloader: 2.4.0
ID: 97 62 F0 60
Not support
```

**Comment by DeqingSun** [comment]
It seems you are using a newer chip. I'll check if https://github.com/ishiyakazuo/ch55x-isptool/commit/151c55e308c1b6c0e93204069938bc114eda363c works.

**Comment by sabas1080** [comment]
@DeqingSun work for me, but i can't get a blink

<img width="897" alt="Captura de Pantalla 2020-08-29 a la(s) 14 13 02" src="https://user-images.githubusercontent.com/2874292/91644460-cc334380-ea01-11ea-8bd2-3e45bb16409f.png">

My schematic work at 3.3v

<img width="572" alt="Captura de Pantalla 2020-08-29 a la(s) 14 05 18" src="https://user-images.githubusercontent.com/2874292/91644480-f1c04d00-ea01-11ea-986f-4242abb86a51.png">

**Comment by DeqingSun** [comment]
I just compiled the 2 versions, would you also try if my file worked for you?

Try to use 5V for main chip to see if the USB work properly. CH552 may not work at 24M with 3.3V power supply.

[vnproch55x.exe.zip](https://github.com/DeqingSun/ch55xduino/files/5145898/vnproch55x.exe.zip)
[vnproch55x.zip](https://github.com/DeqingSun/ch55xduino/files/5145899/vnproch55x.zip)

**Comment by sabas1080** [comment]
Mac work for me, but Windows no

now I have a blink with 12Mhz

**Comment by sabas1080** [comment]
CMSIS DAP working for 12Mhz
<img width="479" alt="Captura de Pantalla 2020-08-29 a la(s) 14 48 10" src="https://user-images.githubusercontent.com/2874292/91644966-b2e0c600-ea06-11ea-84f1-c78fd77c1a9b.png">

**Comment by DeqingSun** [comment]
Good, you may use 16M, that will be a bit faster.
