### ISSUE TITLE
not an issue, just want to know if there is an equivalent to DDRx is AVR mcu, or ODR in STM32

### ISSUE THREAD

**Issue by ranger2012** [DeqingSun/ch55xduino#130]
is it possible to add support for parallel IO to ports. 
write a 8bit  data to ports, rather than setting individual pins.

Thanks,

**Comment by DeqingSun** [comment]
You can do things like P1=0xFF P3=0xFF etc, read the datasheet for pin and register relationship.

Directions are controlled by P1_MOD_OC, P1_DIR_PU, etc. You can also read https://github.com/DeqingSun/ch55xduino/blob/ch55xduino/ch55xduino/ch55x/cores/ch55xduino/wiring_digital.c

**Comment by ranger2012** [comment]
Thank you very much, all is good
________________________________
