### ISSUE TITLE
Is it possible to use sqrt() in ch552?

### ISSUE THREAD

**Issue by ZerooNight** [DeqingSun/ch55xduino#137]
![擷取](https://github.com/DeqingSun/ch55xduino/assets/109935140/ff3bb82b-f42b-4df3-9af2-c61e93708613)
i try sqrt(2),and it shows the error

**Comment by DeqingSun** [comment]
The compiler SDCC does not have sqrt function but has sqrtf. Unfortunately an earlier fix to add --int-long-reent for https://github.com/DeqingSun/ch55xduino/issues/107 did not deal with library properly. So there will be an link error. 

I'll fix the issue later.

**Comment by DeqingSun** [comment]
Please try sqrtf in 0.0.18

**Comment by ZerooNight** [comment]
HI
thanks for the update
but it seems that any code are not working in 0.0.18
the comport doesn't show after burn

take a look at the pic below
i wrote a simple test
after update to 0.0.18,the usage of program space reduce a lot
0.0.18 use 2379
0.0.17 use 9208
![552-1](https://github.com/DeqingSun/ch55xduino/assets/109935140/77c6ccf2-2f4e-4659-a799-ac6bc8ba8f2d)
![552-2](https://github.com/DeqingSun/ch55xduino/assets/109935140/bca121d1-b72b-407e-b862-3216bec52877)

**Comment by DeqingSun** [comment]
Sorry I just realized there was a compiler problem in Windows. If you have a Mac or Linux it would work. I'm still investigating the reason

**Comment by DeqingSun** [comment]
The 0.0.18 has been rolled backed to an earlier compiler built with updated library. Please remove the package and add again.

**Comment by ZerooNight** [comment]
![image](https://github.com/DeqingSun/ch55xduino/assets/109935140/96b24866-75c2-43b2-89e2-c428d3d43348)
works fine now!
thank you very much
