### ISSUE TITLE
WS2812 with v0.0.18

### ISSUE THREAD

**Issue by akita11** [DeqingSun/ch55xduino#142]
Example os WS2812's chase fails to build on v0.0.18 with the following error messages.
```
sdcpp.exe: fatal error: when writing output to : Invalid argument
C:/Users/akita/AppData/Local/Arduino15/packages/CH55xDuino/hardware/mcs51/0.0.18/libraries/WS2812/src/template/WS2812_pins_header.h:7: syntax error: token -> 'dataAndLen' ; column 48
cp:: No such file or director
```
For 0.0.17, it is ok.

**Comment by DeqingSun** [comment]
Sorry, the problem is caused by "clang format" changed the order of include, while I did not automatically test the libraries, nor I add protection to the include statements.

The commit fix the problem
https://github.com/DeqingSun/ch55xduino/commit/1696eea517ffd2a3209256331345032e8103c6ec
