### ISSUE TITLE
Is HID Keyboard + USBSerial (CDC VCP) possible?

### ISSUE THREAD

**Issue by arduino12** [DeqingSun/ch55xduino#143]
**Hi,**

I want my CH552 to act as a USBSerial  (CDC VCP) at start and be able to switch to HID keyboard afterwards.
(will be great to keep the USBSerial simultaneously, but switching between them is good enough for me).

I see that the USBSerial ([USBCDC.c](https://github.com/DeqingSun/ch55xduino/blob/ch55xduino/ch55xduino/ch55x/cores/ch55xduino/USBCDC.c)) is at the core, and the [USBHIDKeyboard.c](https://github.com/DeqingSun/ch55xduino/blob/ch55xduino/ch55xduino/ch55x/libraries/Generic_Examples/examples/05.USB/HidKeyboard/src/userUsbHidKeyboard/USBHIDKeyboard.c) is external,
I found `USBInit` but no way to uninitialize the USB HID Keyboard.
For USBSerial I didn't found any initialize or uninitialize functions.

1. Is it possible to add `USBDeinit` function to the USB examples?
   (maybe name like `Keyboard_begin` , `Keyboard_end`, `USBSerial_begin`, `USBSerial_end`..?)
2. Is it possible to add an example of HID Keyboard + USBSerial?

* Also will be nice to add USBSerial control-line functions (like `getDTR` and `setDTS`, I saw [checking the DTR here](https://github.com/DeqingSun/ch55xduino/blob/ch55xduino/ch55xduino/ch55x/cores/ch55xduino/USBCDC.c#L65)).

**Thanks,
Arad :)**

**Comment by DeqingSun** [comment]
CH552 is not a chip with a lot of RAM or ROM so the USB stuff is hard coded and not able to be uninitialized. 

If you want to use CDC+HID, check this project

https://github.com/Noteolvides/CubeTouch/tree/main/Examples/CDC_KEYBOARD
