### ISSUE TITLE
Support more than 85 LEDs (256 bytes RGB Data) for WS2812

### ISSUE THREAD

**Issue by Kaitoukid93** [DeqingSun/ch55xduino#157]
Curently the library only support 256 bytes of data, so only 85 + 1/3 Leds being controlled
if any N number larger than 256, only N-256 Leds being controlled from the start of the strip

**Comment by DeqingSun** [comment]
Using 16bit buffer length make the looping a bit more complicated and unpredictable for the 8bit machine, especially the CH552 has alignment execution time difference.

Did you try to run 2 neopixel_show consecutively so you don't need to send more than 256 at a time?

**Comment by DeqingSun** [comment]
I've tested:

```
neopixel_show_P1_5(ledData, NUM_BYTES/2); 
neopixel_show_P1_5(ledData+NUM_BYTES/2, NUM_BYTES/2); 
```

And the LED will work properly. As long as the gap between the 2 calls is smaller than reset timing, it should be fine to use multiple "neopixel_show" to send larger array.
