### ISSUE TITLE
Can you add an example about ch559 USB host? This is a very important feature thx

### ISSUE THREAD

**Issue by FBMNBAWA** [DeqingSun/ch55xduino#159]

**Comment by FBMNBAWA** [comment]
Thank you

**Comment by DeqingSun** [comment]
I have not found a good framework for USB host. But you generally can copy example from WCH directly because you don't need interrupts for host.

**Comment by relaxibus** [comment]
what about to port this project to Arduino?
https://github.com/atc1441/CH559sdccUSBHost

**Comment by DeqingSun** [comment]
@relaxibus That is a working example, not a framework. You can not modify the code unless you are an expert in USB. But you won't need that code if you are an expert.
