### ISSUE TITLE
Keyboard Matrix Problem

### ISSUE THREAD

**Issue by shzang** [DeqingSun/ch55xduino#166]
I am using the ch55xduino project to make a pad keyboard. At present, the hardware has been completed, but I found that the code of the keyboard in the project example is 3 keys. I found some projects on the network, and one pin corresponds to one key. I don't know how to write the matrix more efficiently. Can you provide some examples?

**Comment by shzang** [comment]
To add, the core of my pad keyboard is wch552g.

**Comment by DeqingSun** [comment]
Matrix key reading is a general electronic problem, and not specific to this repo. I do not have any code sample either. You should read how other people do matrix reading.
