### ISSUE TITLE
About these three buttons，Spacebar， NUM LOCK， SCROLL LOCK

### ISSUE THREAD

**Issue by Mr-ShiYi** [DeqingSun/ch55xduino#170]
hello
I didn't find this file in USBHIDKeyboard，Spacebar， NUM LOCK， SCROLL LOCK，These three buttons
Can you tell me why these three corresponding buttons are not available?

**Comment by DeqingSun** [comment]
fixed with
https://github.com/DeqingSun/ch55xduino/commit/9752656ae3ab8bc945ef54cf7464c5126e5ba419
