### ISSUE TITLE
enhancement: add CH551

### ISSUE THREAD

**Issue by nerdralph** [DeqingSun/ch55xduino#2]
It has 10kB of flash available according to the specs, though my testing reveals 12kB usable.  It only has 512B of xRAM, no ADC, and one UART.  Adding a board or MCU option for the CH551 would make ch55xduino more foolproof for newbies that don't understand the differences between the different devices.

**Comment by DeqingSun** [comment]
Will do.

**Comment by DeqingSun** [comment]
partially fixed https://github.com/DeqingSun/ch55xduino/commit/de114480dc5fa533be5d3353ad079149ab5b48a5

Need test on CH551 to see if it is necessary to disable ADC and 2 touch channels.

**Comment by DeqingSun** [comment]
ADC and 2 touch channel just give you empty results on ch551. Not a big deal.
