### ISSUE TITLE
mini dev board using breadboard

### ISSUE THREAD

**Issue by swuecho** [DeqingSun/ch55xduino#20]
![image](https://user-images.githubusercontent.com/666683/98065039-9f325f80-1e8e-11eb-8e2f-05f06e5ea841.png)

**Comment by swuecho** [comment]
![image](https://user-images.githubusercontent.com/666683/98065155-e4569180-1e8e-11eb-87c8-b6611b78ef9e.png)

add one key to send mouse left click to computer.

**Comment by swuecho** [comment]
pull request instead.

**Comment by ichirowo** [comment]
Hello.
Have you completed the code to move the mouse with the ch55xduino?
I am having trouble figuring out how to make a mouse.
I would appreciate it if you could share it with me.

Best regards
