### ISSUE TITLE
CMSIS-DAP example fails on Win7

### ISSUE THREAD

**Issue by nerdralph** [DeqingSun/ch55xduino#23]
I've tried both with a CH552 and a CH551 module.
After power cycling the module, windows detects it, but under device status, the device status is "device cannot start (Code 10)"
The UsbSerialAdaptor example works fine.

**Comment by nerdralph** [comment]
I reverted to v0.0.5, and get the same problem.

**Comment by DeqingSun** [comment]
Thanks. I can reproduce the same error on Win7. Will take a look.

**Comment by DeqingSun** [comment]
It seems a drive issue with the same PID. 
Try this one
https://github.com/DeqingSun/ch55xduino/tree/playground/ch55xduino/ch55x/libraries/Generic_Examples/examples/05.USB/CMSIS_DAP

**Comment by nerdralph** [comment]
That fixes it.  Now it detects as a HID device, and
`openocd -f interface/cmsis-dap.cfg`
recognizes it as a SWD device.

**Comment by DeqingSun** [comment]
Good. It has been tested with OPENOCD on Mac in Arduino IDE with ATSAMD21G18. Worked when I select "ATMEL EDBG" as programming. Programmed bootloader on ATSAMD21G18 well.

Also worked with Keil 5 on Win7 with STM32F103C8T6. Both tested in programming and debugging.
