### ISSUE TITLE
This is not bug. Thank you ^^

### ISSUE THREAD

**Issue by thinhx2** [DeqingSun/ch55xduino#26]
![IMG_20201215_155517](https://user-images.githubusercontent.com/16272934/102198126-994f8580-3ef4-11eb-8e34-d738f3b14fee.jpg)

Thank you, working fine

**Comment by thinhx2** [comment]
Btw i have a question : possible to port it to nuvoton w78e0 (preinstalled bootloader with press reset button to flash) or stc 8051 (preinstalled bootloader with disconnect vcc and reconnect vcc to flash)?

**Comment by DeqingSun** [comment]
@thinhx2 Definitely possible. You may need to customize the tools to fit your tool chain. And if you need to upload the sketch with Arduino. You may need to design a special serial adaptor to power cycle target. If you only need to press reset button, just refer to Arduino Uno circuit.

**Comment by thinhx2** [comment]
Thank for suggest. I will look to stcgal for stc
