### ISSUE TITLE
CMSIS-DAP very slow

### ISSUE THREAD

**Issue by nerdralph** [DeqingSun/ch55xduino#29]
The speed control is of little use, since the bit-bang SWD code is so slow, it can't go any faster than 1/60th of the system clock.  With a CH552 running at 16MHz, the SWD frequency was ~260kHz, even though I chose a 1MHz clock.  I can think of a few ways to improve performance.
1) Use the SPI peripheral on P1.7 & P1.5.  The SPI clock can run at 1/2 the CPU clock.  I'm not sure if it can send less than 8 bits, so the ACK sequence may still have to be bit-banged.
2) Optimize the bit-bang code for maximum speed.  I tried defining SW_WRITE_BITS as `SWD = (bits)&1; SWK = 0; SWK = 1;`, and measured the speed at ~1.25MHz.  I'm not aware of any devices that can't handle a clock of at least 1.33MHz (8MHz/6 for some STM32 devices).   Lower clock rates could still be supported by modifying the PLL.  6MHz, the lowest for full-speed USB operation, would give a SWD clock of 400-500kHz.
3) Change the bit-bang timing to use a busy loop.  nop + djnz reg gives a reliable delay that is a multiple of 6 cycles.  Since SWD data is latched after the rising edge of SWCLK, the delay would only be needed after SWK = 1.  This could support speeds from 10kHz to 1MHz.

The slow speeds is most noticeable during uploads.  So far I've only tested with small programs of a few kB, but for people using large programs on devices with >64kB of flash, faster SWD speeds should make a big difference.  Without buffered HID requests, the maximum USB data throughput will be less than 32KB/s.  With bit-banged SWD communications at 1MHz, there should be enough CPU cycles left to get a system throughput of 20-30KB/s.

**Comment by DeqingSun** [comment]
There is a tons of optimization can be done to improve the speed and someone achieved 300KB/s with CH558. However, the optimization takes a lot of work to do and that has lower priority.
