### ISSUE TITLE
comment bug

### ISSUE THREAD

**Issue by nerdralph** [DeqingSun/ch55xduino#38]
You have the endpoint comments backwards.  The first one is OUT, 2nd one is IN.
https://github.com/DeqingSun/ch55xduino/blob/ch55xduino/ch55xduino/ch55x/libraries/Generic_Examples/examples/05.USB/CMSIS_DAP/src/CMSIS_DAPusb/USBconstant.c#L47

bEndpointAddress  bit 7 direction 0 = Out, 1 = In

I fixed it and cleaned up the descriptors a bit more in my version.
https://github.com/nerdralph/ch554_sdcc/blob/master/examples/CMSIS_DAP/USBconstant.c#L55

**Comment by DeqingSun** [comment]
Thanks for pointing out.
Fixed in https://github.com/DeqingSun/ch55xduino/commit/36d05a5ca3c3ad16f79e3f47cfc98fb93a3fec82
