### ISSUE TITLE
endpoint buffers too small

### ISSUE THREAD

**Issue by nerdralph** [DeqingSun/ch55xduino#40]
I think they should be 10 bytes, not 8.
https://github.com/DeqingSun/ch55xduino/blob/ch55xduino/ch55xduino/ch55x/libraries/Generic_Examples/examples/05.USB/CDCinUserCode/src/userUsbCdc/USBhandler.c#L13

**Comment by DeqingSun** [comment]
EP1_ADDR is 10
EP2_ADDR is 20
There is a 2 byte gap.

**Comment by nerdralph** [comment]
OK, missed that.  I was just looking at the array size.
