### ISSUE TITLE
Can I make a combined HID for keyboard and mouse?

### ISSUE THREAD

**Issue by ichirowo** [DeqingSun/ch55xduino#47]
I found a sample program for the keyboard HID, so I understood it. I looked for a sample program for the mouse, but there was none.
Please let me know if you have a sample program that is easy to understand.
Thank you very much.

**Comment by DeqingSun** [comment]
@ichirowo Not a keyboard and mouse combination yet but a keyboard and consumer combination.
https://github.com/DeqingSun/ch55xduino/tree/48ab63be79ea0ff72d5b5bb04ace5cf76b6a588a/ch55xduino/ch55x/libraries/Generic_Examples/examples/05.USB/HidMediaKeyboard

But they share the same idea of using 2 reports for 2 functions. I'll do a keyboard and mouse in the next 2 weeks.

**Comment by ichirowo** [comment]
@DeqingSun 
Appreciate the reply. The keyboard and mouse complex was forked and created by this person. Why don't you request a merge?

https://github.com/betaEncoder/ch55xduino/tree/ch55xduino/ch55xduino/ch55x/libraries/Generic_Examples/examples/05.USB

**Comment by DeqingSun** [comment]
@ichirowo 
Thanks for the notice. I did not know there was this fork. Will merge.
