### ISSUE TITLE
Accessing BOD settings

### ISSUE THREAD

**Issue by gimsonrobotics** [DeqingSun/ch55xduino#49]
We have having some trouble with the CH552 chips, programmed via the Arduino IDE, becoming unstable if the supply voltage drops too much, rather than reverting to a consistent off state. Does anyone contributing on here know if there are BOD settings that might be accessible via a future update? Thanks!

**Comment by DeqingSun** [comment]
This chip does not come with an internal BOD. An external one will be required for your application.
