### ISSUE TITLE
fix code formatting

### ISSUE THREAD

**Issue by nerdralph** [DeqingSun/ch55xduino#5]
I noticed most of the code uses tabs, but some uses spaces for indentation.  Either use tabs everywhere or spaces everywhere.
https://github.com/DeqingSun/ch55xduino/blob/ch55xduino/ch55xduino/ch55x/cores/ch55xduino/wiring_digital.c

**Comment by DeqingSun** [comment]
fixed

https://github.com/DeqingSun/ch55xduino/commit/851dd7631b0e6e6fdb3f6024493c031db532b34c
