### ISSUE TITLE
CH552 can not communicate with 230400 baudrate on 24Mhz

### ISSUE THREAD

**Issue by wukongxuetang** [DeqingSun/ch55xduino#51]
CH552 UsbSerial can  communicate properly with 230400 baudrate on 24Mhz,But Serial0 can not,I can use with 115200.
 Which can communicate with 230400 in CH55x?

**Comment by DeqingSun** [comment]
check https://github.com/DeqingSun/ch55xduino/issues/33
UsbSerial does not actually send data in the baudrate you set.
