### ISSUE TITLE
WinUSB driver for on-chip boot loader mode.

### ISSUE THREAD

**Issue by AnonymousChatter** [DeqingSun/ch55xduino#52]
Just would like to check if anyone have any further success with installing Window's WinUSB driver with CH55x on chip boot loader mode.

The reason I am still "stubborn" on staying with WinUSB instead of libUSB is because Chrome's WebUSB only works with WinUSB driver (Correct me if I am wrong).

Thank you.

**Comment by nulllaborg** [comment]
i find vnproch55x tools is only use libusb not WINUSB, may can rebuild vnproch55x support  WINUSB

**Comment by DeqingSun** [comment]
@AnonymousChatter Using CH375 driver is possible and recommended now.

https://github.com/DeqingSun/ch55xduino/blob/80d298d92efb4f4f9473f86be5710ac8f1b719b4/README.md?plain=1#L56
