### ISSUE TITLE
How to Disable Reset Input Pin

### ISSUE THREAD

**Issue by Kaitoukid93** [DeqingSun/ch55xduino#53]
I want to Disable RST pin, so the status of that pin will not reset the chip
I have made a mistake on a pcb that I use RST pin to control a LED, now I want to use pin 1.7 instead by shorting P1.7 and RST with solder bridge, but by doing that, the chip hang on reset
thanks for help

**Comment by DeqingSun** [comment]
@Kaitoukid93 you will need to change the configuration byte to disable reset pin. If you are using a ch55x chip, the configuration will not be changed by the Arduino tool chain.

You can use a windows computer and the wch tool to change the configuration

**Comment by Kaitoukid93** [comment]
Thanks, I found the option in WCHisp,
