### ISSUE TITLE
Use type-generic macros

### ISSUE THREAD

**Issue by leo60228** [DeqingSun/ch55xduino#54]
According to the README:
> There is no free C++ compiler for MCS51 chip, we can not use polymorph functions. So you can not expect the compiler will choose a function according to the parameter's type.

C11 adds [`_Generic`](https://en.cppreference.com/w/c/language/generic) for this purpose. Here's a trivial example: https://godbolt.org/z/Yv8sznf3v

However, this currently can't be used for `print` due to an [SDCC bug](https://sourceforge.net/p/sdcc/bugs/3255/).

**Comment by DeqingSun** [comment]
@leo60228 thanks for this info. I'll check if this can be implemented into the package.

**Comment by DeqingSun** [comment]
@leo60228 Frankly speaking I have no idea what "_Generic" means or how it compiles (yet). But it seems work. I'll see how to add it into the package.

![Screen Shot 2021-09-29 at 9 07 01 AM](https://user-images.githubusercontent.com/1385273/135274554-aee1c0bb-6175-4109-b213-523d313541a9.png)

**Comment by leo60228** [comment]
_Generic is a relatively new feature (C99 had polymorphic functions in the standard library, but those were implemented in a compiler-specific way until C11). SDCC supports it but there's several open bugs. I don't think it's usable for `print` yet, but it could be with some bugfixes, and might be useful for other functions.

**Comment by DeqingSun** [comment]
@leo60228 Sorry I ask the question before I learn some basics about  _Generic. Why you think it is not usable for print? It seems my sketch compiles and works as expected.

**Comment by leo60228** [comment]
There's a cryptic compiler error if you use it with a pointer, which is why
char* was commented out. I linked an existing bug report for this in the
original issue.

**Comment by DeqingSun** [comment]
@leo60228 Not sure why it works on my side. I'm using a pre-built mac build.11630 from the official website. 


![Screen Shot 2021-09-29 at 9 18 34 AM](https://user-images.githubusercontent.com/1385273/135276350-3cc69da7-83b5-4c29-8e14-7f06b15ce7d6.png)

**Comment by DeqingSun** [comment]
@leo60228 Thank you and I get it when trying to use the pointer.

```
Internal error: validateLink failed in SPEC_NOUN(type) @ /Users/sdcc-builder/build/sdcc-build/orig/sdcc/src/SDCCast.c:5401: expected SPECIFIER, got DECLARATOR
```

I'll subscribe to that ticket and see when it get fixed. Not supporting pointer makes implementing the  _Generic to print pointless.

**Comment by DeqingSun** [comment]
Update: The bug fixing is now funded. Wish it get fixed soon

https://sourceforge.net/p/sdcc/wiki/SDCC-STD-UX/

**Comment by DeqingSun** [comment]
Generic is functional after SDCC commit 13402. 

This repo now supports Generic for print.

https://github.com/DeqingSun/ch55xduino/blob/ch55xduino/ch55xduino/ch55x/cores/ch55xduino/genericPrintSelection.h
