### ISSUE TITLE
Can I send media control keypresses via HID Keyboard?

### ISSUE THREAD

**Issue by foadyousefi** [DeqingSun/ch55xduino#59]
First, thanks for this awesome work.

I am able to compile and flash the examples. I was wondering how can I send media control commands/keypresses like volume up and down, next, pause and play. 
Where can I find a list of available key commands?

The price and minimal circuit requirements of this microcontroller make it ideal for most DIY projects, especially something like macro pads. Setting up a ch552 is way way easier than something like Atmega32u4.

**Comment by DeqingSun** [comment]
You do need to make some modifications to the example. Such as adding consumer control in ReportDesc. It will definitely work.

**Comment by foadyousefi** [comment]
Thanks for your response. 
Sorry for my dumb question, but can you please give me an example? It sounds a bit too complex for me.

**Comment by DeqingSun** [comment]
I will try to add that but it may take a few months until I have time to do so.

**Comment by foadyousefi** [comment]
@DeqingSun Any news here?

**Comment by DeqingSun** [comment]
@foadyousefi 
Try
https://github.com/DeqingSun/ch55xduino/tree/48ab63be79ea0ff72d5b5bb04ace5cf76b6a588a/ch55xduino/ch55x/libraries/Generic_Examples/examples/05.USB/HidMediaKeyboard

**Comment by foadyousefi** [comment]
@DeqingSun Thanks, I will try and let you know the results.

**Comment by foadyousefi** [comment]
@DeqingSun I tried and it's working perfectly. Thank you.
