### ISSUE TITLE
fail to write

### ISSUE THREAD

**Issue by bamboo-master** [DeqingSun/ch55xduino#62]
I get error when try load scetch from arduino ide.

libusb-win32 driver

Load file as hex
   Loaded 5899 bytes between: 0000 to 1738
Found Device CH552
Bootloader: 2.3.1
ID: C8 68 B4 44
XOR Mask: 28 28 28 28 28 28 28 7A 
Read ID: Fail

or

Load file as hex
   Loaded 5899 bytes between: 0000 to 1738
Read Detect: Fail

CH375  driver

Load file as hex
   Loaded 5899 bytes between: 0000 to 1738
Found no CH55x USB

Also in WCHISPTool with CH375 driver i get error 
Device is started
BTVER 02.31
Erasing...
99%

if i manualy set dfu made i get 
75%
erase dataflash error
failure

Initially, everything worked.

I think the read-only mode has turned on.

Tried other computers the result is the same
What can be done?

**Comment by DeqingSun** [comment]
Test another chip. Also this is a question better asked at the WCH customer service place.
