### ISSUE TITLE
how to set ch552 softi2c address 如何设置ch552的i2c地址

### ISSUE THREAD

**Issue by wukongxuetang** [DeqingSun/ch55xduino#64]
could not found how to set ch552 i2c address while using softi2c library,Would you like to provide an example using softi2c with multiple ch552 communication？Thanks

在softi2c库里没有找到设置i2c地址的函数，多个ch552使用i2c通讯时，如何设置，可以提供一个多ch552设备间softi2c通讯的例子吗，谢谢

**Comment by DeqingSun** [comment]
The current softi2c library does not support slave mode yet. So no need to set I2C address.
