### ISSUE TITLE
support for bootloader 2.5.0

### ISSUE THREAD

**Issue by sgmklp** [DeqingSun/ch55xduino#65]
I use the CH552 to try it, but get this
![image](https://user-images.githubusercontent.com/74038035/159484712-3e797c58-6dc4-43b5-bf70-dc630a58eb05.png)
Then I see the JavaScrip Code, find it seems not support bootloader 2.5.0

**Comment by DeqingSun** [comment]
Thanks for reporting this.

Can you try to comment this line on the js file and let me know if it works for you?

https://github.com/DeqingSun/ch55xduino/blob/78d01729a897dd2080c855575f0042dc18c31fc4/bootloaderWebtool/ch55xbl.js#L99

If it works I'll update the Arduino tool. Otherwise, would you let me know where you get the chip? So I can get one and test.

**Comment by sgmklp** [comment]
I try the js,but it can't open my device in the browser
![image](https://user-images.githubusercontent.com/74038035/159508246-7fffb690-5e7c-486c-825f-730a741a04ac.png)
And this is the link for my broad
https://item.taobao.com/item.htm?spm=a1z09.2.0.0.63eb2e8duvXXHX&id=669901203749&_u=m20acmm8g69595
I will buy a new one and try to test the new.

**Comment by DeqingSun** [comment]
I'll compile a new windows version later today. That error is a permission problem not a hardware problem

**Comment by DeqingSun** [comment]
@sgmklp please try this tool. You can replace the original one in

```
C:\Users\YOUR USER NAME\AppData\Local\Arduino15\packages\CH55xDuino\tools\MCS51Tools
```

[vnproch55x.exe.zip](https://github.com/DeqingSun/ch55xduino/files/8327159/vnproch55x.exe.zip)

This file used the same protocol but accepts 2.5.0 as bootloader version.

**Comment by DeqingSun** [comment]
@sgmklp Does the updated version work with the 2.5.0 bootloader?

**Comment by sgmklp** [comment]
Yes, i try it today, and it work. Thanks

**Comment by DeqingSun** [comment]
There was a logic bug that made the tool only support 2.5.0 version of bootloader. 

This one is better.
[vnproch551_exe_20220331.zip](https://github.com/DeqingSun/ch55xduino/files/8390855/vnproch551_exe_20220331.zip)

-------

For my own future reference. remove zadig driver and restore official one:

![WechatIMG2040](https://user-images.githubusercontent.com/1385273/161099930-ecdaf274-fe2b-4cbe-bfe6-818d3670dc9d.png)
![WechatIMG2043](https://user-images.githubusercontent.com/1385273/161099942-232b38dc-d42b-444a-b551-82de723bd570.png)

**Comment by sgmklp** [comment]
OH, thanks.
