### ISSUE TITLE
Change USB DM ( p3.7) pinMode problem

### ISSUE THREAD

**Issue by Kaitoukid93** [DeqingSun/ch55xduino#69]
I have the following code in setup just for detecting the type of host device. The detection is working wonderful!
When I tried to set the pinMode of P3.7 (USB DM) to Output and drive it low, it did not change the line state ( the line is pulled high by 10k resistor in the host side)
Is anything i'm doing wrong or the pinMode can not change when using USB Library?
Thanks
```
void setup()
{

  pinMode(36, INPUT);
  pinMode(37, INPUT);
  bool DMState;
  DMState = digitalRead(37);
  if (DMState == HIGH)
    Host = PowerLED;
  else
    Host = Computer;
  switch (Host)
  {
    case Computer: // this USB is attached to Host Computer

      USBInit();

      }

      break;

    case  PowerLED : // this usb is attached to the  Customized power brick

     
      pinMode(37, OUTPUT);
      digitalWrite( 37, LOW); //drive DM LOW to notify the power brick
      
      break;
  }
```

**Comment by DeqingSun** [comment]
When USB is enabled, bUSB_IO_EN is set to 1, and you can not make the pin to output. The datasheet mentioned this.

**Comment by Kaitoukid93** [comment]
Thanks! The datasheet is partly translated and a bit hard to understand
Do you think below is the best options?
dummyPin is other IO pin with full function and connect to P3.7 with a 1K resistor
```
#define dummyPin  PX.X
void setup()
{
  pinMode(dummyPin, INPUT);
  pinMode(36, INPUT);
  pinMode(37, INPUT);
  bool DMState;
  DMState = digitalRead(37);
  if (DMState == HIGH)
    Host = PowerLED;
  else
    Host = Computer;
  switch (Host)
  {
    case Computer: // this USB is attached to Host Computer

      USBInit();

      }

      break;

    case  PowerLED : // this usb is attached to the  Customized power brick

     
      pinMode(dummyPin, OUTPUT);
      digitalWrite( dummyPin, LOW); //drive DM line LOW to notify the power brick
      
      break;
  }

```

**Comment by DeqingSun** [comment]
If you are sure you are not going to use USB anymore, try

PIN_FUNC &= ~bUSB_IO_EN;

Before you use the gpio again.

**Comment by Kaitoukid93** [comment]
> If you are sure you are not going to use USB anymore, try
> 
> 
> 
> PIN_FUNC &= ~bUSB_IO_EN;
> 
> 
> 
> Before you use the gpio again.

Thanks! That's exactly what I need. When the host is not the computer,I don't need usb anymore
