### ISSUE TITLE
Add support CH559

### ISSUE THREAD

**Issue by sabas1080** [DeqingSun/ch55xduino#7]
Hi @DeqingSun 

Please add support for CH559

**Comment by DeqingSun** [comment]
Hi @sabas1080 
At this moment I don't have a CH558/559 to test.

**Comment by alijani1** [comment]
CH559 support would be fantastic.  there is a major void in the market for USB hosts that work on Arduino, especially dual port ones.

**Comment by DeqingSun** [comment]
@sabas1080 @alijani1 Now there is support for CH559.

**Comment by sabas1080** [comment]
Thanks @DeqingSun

**Comment by alijani1** [comment]
Super. Will try it out and let you know.  Thank you!
