### ISSUE TITLE
24 Mhz external crystal oscillator clock source

### ISSUE THREAD

**Issue by reppad** [DeqingSun/ch55xduino#70]
Hi,

I recently received a new [development module based on CH552T](https://github.com/WeActTC/WeActStudio.CH552CoreBoard).
This little module looks promising, it features USB-C, a LED on P3.0, a reset button, a button connected to p3.6 to trigger the bootloader and... an external 24 MHz oscillator.

It would be really nice to be able to choose the external oscillator as the clock source in the menu of the Arduino IDE.

Many thanks for your work on this project!

**Comment by DeqingSun** [comment]
Will do.

Before this is implemented in menu, you can do:

```
    //switch XT
    SAFE_MOD = 0x55;
    SAFE_MOD = 0xAA;
    CLOCK_CFG |= bOSC_EN_XT;
    delayMicroseconds(10000);
    SAFE_MOD = 0x55;
    SAFE_MOD = 0xAA;
    CLOCK_CFG &= ~bOSC_EN_INT;
    SAFE_MOD = 0x00;
```

**Comment by DeqingSun** [comment]
Added in https://github.com/DeqingSun/ch55xduino/commit/b48cdc71b8f850a17b862c753d7f62b2cbe0cd81
