### ISSUE TITLE
PlatformIO support

### ISSUE THREAD

**Issue by danielkucera** [DeqingSun/ch55xduino#73]
Hello,
would it be please possible to add support for Platformio besides Arduino IDE?

It already has a support for compiling for this architecture, see:
https://github.com/platformio/platform-intel_mcs51/pull/29

**Comment by DeqingSun** [comment]
It seems the platformio branch is already working?

**Comment by danielkucera** [comment]
Which branch do you mean? What do yo mean by "working" ?

**Comment by DeqingSun** [comment]
The pr you linked is already merged. So that means the platform io already work with ch559

**Comment by kahoch** [comment]
> The pr you linked is already merged. So that means the platform io already work with ch559

If select ch559 board, framework option is dimmed. Anyone knows how to use arduino framework in PIO?

**Comment by danielkucera** [comment]
> The pr you linked is already merged. So that means the platform io already work with ch559

Yes, ch559 is supported with basic SDK but Arduino (ch55xduino) is not supported as @kahoch pointed out.

**Comment by DeqingSun** [comment]
The support of Platformio is very generic and ch55xduino relied on tons of hack to get the compiler work. I'm not sure if Platformio is capable to do the same hack, even if it can, it will require a tons of work.

**Comment by KenwoodFox** [comment]
Sorry to bump, did you ever get this working with platformio @danielkucera? I looked over that PR that was published they did mention existing arduino specific support for the CH55x,
I don't have a 559 though i have a 552

I don't think we're too far off from PIO support, the existing .json at the root is close to the platform reqs parsable by pio?
