### ISSUE TITLE
Arduino内无法使用namespace

### ISSUE THREAD

**Issue by hanbingniao1** [DeqingSun/ch55xduino#77]
您好！
我在使用namespace的时候，arduino如下报错:
Syntax error, declaration ignored at 'namespace'
 '"' ; column 14
syntax error: token -> '}' ; column 1
经过多次测试，同样代码在默认的arduino板上编译通过，切换至ch55x后报错

**Comment by kaofishy** [comment]
`namespace` is only for C++, there is no C++ support in ch55xduino since no free C++ compiler for 8051.

**Comment by hanbingniao1** [comment]
> `namespace` is only for C++, there is no C++ support in ch55xduino since no free C++ compiler for 8051.

Think you!
