### ISSUE TITLE
link error with USER_CODE option

### ISSUE THREAD

**Issue by nerdralph** [DeqingSun/ch55xduino#8]
?ASlink-Warning-Undefined Global '_USBInterrupt' referenced by module 'main'

**Comment by DeqingSun** [comment]
I didn't find a way for sdcc to do weak declaration. So USBInterrupt is refered in main for user to declare it. 

If you check the 2 examples, they both have it declared. If you don't need USB, just do an empty function.

**Comment by DeqingSun** [comment]
maybe it is possible to do overloading by using a library

https://sourceforge.net/p/sdcc/mailman/message/35824985/

**Comment by DeqingSun** [comment]
Fixed with https://github.com/DeqingSun/ch55xduino/commit/f3a5db8d16c8a0e36b8c7d2d0726ad286d349db9

An additional weakOverride.c works.

**Comment by nerdralph** [comment]
Nice.  I've done something similar with my picoUART library.

**Comment by nerdralph** [comment]
With an empty USBInterrupt function, it links and uploads, but the code doesn't run; it seems to stay in the bootloader.  After a power cycle, the same thing.

**Comment by DeqingSun** [comment]
@DeqingSun Are you using a delay?

That was a bug because I didn't enable EA by default. Now it should work with https://github.com/DeqingSun/ch55xduino/commit/cde2fd71a72cd5b44f061124bd7d433ee1aefbf6

**Comment by nerdralph** [comment]
Yes, I was testing with a basic blink sketch.
