### ISSUE TITLE
HID Keyboard example question

### ISSUE THREAD

**Issue by WayneChen0109** [DeqingSun/ch55xduino#81]
Hellow 
I use HID Keyboard this example  and I compile code but message box show :
#error "This example needs to be compiled with a USER USB setting"

i don't know this error message  mean

**Comment by DeqingSun** [comment]
Check the option in the menu, I don't have a computer right now

**Comment by DeqingSun** [comment]
<img width="582" alt="Screen Shot" src="https://user-images.githubusercontent.com/1385273/184282858-93d4c03c-c9d3-4eca-99b5-f8f2f148f37d.png">
