### ISSUE TITLE
SPIFlash library

### ISSUE THREAD

**Issue by jnthas** [DeqingSun/ch55xduino#84]
Hi there! I've been using the ch55xduino for the last few days and I missed a library to handle flash memory chips so I'm porting one. 
As this kind of chip uses SPI and the SPI library is already available it wasn't hard porting a library to ch55xduino.

Currently it's supporting `Winbond W25Qxx`. I'm finishing the implementation and testing and would like to know If I should open a PR to your repo or create a new repo for the library?

**Comment by DeqingSun** [comment]
Please put it in the example folder of the spi library, and then start a PR

Thanks for your contribution
