### ISSUE TITLE
Enter and Exit low power modes examples

### ISSUE THREAD

**Issue by danilomna** [DeqingSun/ch55xduino#89]
Hi,

Would be possible add low power examples to the lib?
This kind of feature is essential to battery powered devices and would be very usefull.

Enter Low power, sleep mode, deep sleep
Exit Low power, IO level change, timer interrupt, watchdog

Regards

Danilo

**Comment by DeqingSun** [comment]
Read the datasheet before you ask questions like that.

This chip does not have that many sleep features

**Comment by danilomna** [comment]
Read the datasheet before answer a question like that.

The chip have sleep feature.

![image001](https://user-images.githubusercontent.com/57544850/192206860-35cde8dd-0923-4073-8923-343f83a5edd3.png)

**Comment by danilomna** [comment]
Please reopen issue.

**Comment by guibom** [comment]
I'm curious about this too... I checked the datasheet and can see some defined registers on ch5xx.h, to enable specific wake up events. 
But I'm not sure how to use those.
