### ISSUE TITLE
pull improvements from ch554_sdcc

### ISSUE THREAD

**Issue by nerdralph** [DeqingSun/ch55xduino#9]
For example:
https://github.com/Blinkinlabs/ch554_sdcc/issues/19

It seems you copied most of the HardwareSerial0 code from debug.c.  x1 and x2 should be changed here:
https://github.com/DeqingSun/ch55xduino/blob/ch55xduino/ch55xduino/ch55x/cores/ch55xduino/HardwareSerial0.c#L23

**Comment by DeqingSun** [comment]
Fixed in
https://github.com/DeqingSun/ch55xduino/commit/b67ded02cc423e7808fe95018d06adceb98cdb17
Seems save about 60 bytes and some xram space
Will be merged into main branch in the next release.
