### ISSUE TITLE
Uploading the program issue

### ISSUE THREAD

**Issue by slamik3** [DeqingSun/ch55xduino#93]
I uploaded an example of a massstorage program via arduino ide, and different code cannot be uploaded to the device anymore. It looks like a usb disk and has no serial port. WeAct CH552 Mini

https://github.com/DeqingSun/ch55xduino/blob/ch55xduino/ch55xduino/ch55x/libraries/Generic_Examples/examples/05.USB/MassStorage/MassStorage.ino

**Comment by DeqingSun** [comment]
That is expected. You need to manually enter bootloader mode and upload, if you do not have serial port over USB.

Hold the button and plug in the board.
