### ISSUE TITLE
Multiple I2C interface possible?

### ISSUE THREAD

**Issue by greenwyrt** [DeqingSun/ch55xduino#96]
Is it possible to initialize two or more i2c interfaces?

To my understanding, the softi2c lib has one i2c interface since the pins are not passed in like in the wire library. Could the library allow passing pin numbers in and have multiple i2c (like wire and wire1)?

Having multiple i2c would make it easier to work with chips that have the same address.

**Comment by DeqingSun** [comment]
I did not try it but I think it is possible, just finish the current transaction, set scl_pin and sda_pin to new value, the call I2CInit(). The library will switch to new pins.

**Comment by greenwyrt** [comment]
Thank you!

I haven't tried it out yet but that sounds very plausible so I will close this issue.
